name: Issue Handler

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Add triage label
        run: |
<<<<<<< HEAD
          gh issue edit "$ISSUE_URL" --add-label "bug"  # 这里打bug标签是为了测试工作流是否正常工作
=======
          gh issue edit "$ISSUE_URL" --add-label "bug"
>>>>>>> 7e902110b81a6b83e4de0a75b5025e508b4a3e5b
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

      - name: Add comment
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "感谢提交 Issue！系统已经收到，我们会进行初步处理。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
